### ISSUE TITLE
Skipped module 'Lamp' due to an error

### ISSUE THREAD

**Issue by r-hassan-zz** [zainozzaini/RaspberryPi-Jasper-LED#1]
Hello, 

I installed as per the instruction provided in Read.ME file. When starting Jasper the following error comes up ...

WARNING:client.brain:Skipped module 'Lamp' due to an error.
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 43, in get_modules
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/pi/jasper/client/modules/Lamp.py", line 3, in <module>
    import RPi.GPIO as GPIO ## Import GPIO Library
SetupException: This module can only be run on a Raspberry Pi!

Please advice.
## 

Raqueeb Hassan
Bangladesh

**Comment by r-hassan-zz** [comment]
Actually, for RP2 you have to run updated version of RPi.GPIO.
